{% set name = "cpp-argparse" %}
{% set version = "3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/p-ranav/argparse/archive/v{{ version }}.tar.gz
  sha256: d01733552ca4a18ab501ae8b8be878131baa32e89090fafdeef018ebfa4c6e46

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]

test:
  commands:
    - test -d ${PREFIX}/include/argparse  # [unix]
    - test -f ${PREFIX}/include/argparse/argparse.hpp  # [unix]
    - if exist %LIBRARY_PREFIX%\include\argparse\argparse.hpp (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/p-ranav/argparse
  summary: 'Argument Parser for Modern C++ '
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/p-ranav/argparse

extra:
  recipe-maintainers:
    - p-ranav
    - SylvainCorlay
    - JohanMabille
    - Hind-M
